trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Installing required packages"
      sudo apt-get update
      sudo apt-get install -y python3-pip
      pip3 install python-telegram-bot
      chmod +x *
      
      echo "Running the Telegram Bot"
      python3 devil.py
    displayName: 'Run Telegram Bot'
