trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing required packages..."
    pip install telebot
    pip install pymongo aiohttp
  displayName: 'Install Packages'

- script: |
    echo "Changing permissions for files..."
    chmod +x *
  displayName: 'Change File Permissions'

- script: |
    echo "Running the Python script..."
    python3 devil.py
  displayName: 'Run Python Script'
